databases:
  - name: ytsummarizer-db
    plan: free
    ipAllowList: []

services:
  - type: web
    name: ytsummarizer-backend
    runtime: docker
    plan: free
    dockerContext: ./ytsummarizer/ytsummarizer
    dockerfilePath: ./ytsummarizer/ytsummarizer/Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: ytsummarizer-db
          property: jdbcConnectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ytsummarizer-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ytsummarizer-db
          property: password
      - key: GEMINI_API_KEY
        value: "PLACEHOLDER_KEY"

  - type: web
    name: ytsummarizer-frontend
    runtime: docker
    plan: free
    dockerContext: ./yt-summarizer-frontend/yt-summarizer
    dockerfilePath: ./yt-summarizer-frontend/yt-summarizer/Dockerfile
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: ytsummarizer-backend
          property: host