server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ytsummarizer
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY:PLACEHOLDER_KEY}
        chat:
          options:
            model: gemini-2.5-flash
          retry:
            max-attempts: 1

# Parallel configuration block for Scraping API
scrapingant:
  api-key: ${SCRAPING_ANT_API_KEY:PLACEHOLDER_KEY}